<?php

namespace AppBundle\Repository;

/**
 * ImageGallerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageGallerieRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @return array
     */
    public function findGallerie(){
        //requête limitant l'affichage à 50 images,
        // Intéressant : le findBy permet findBy(array $column =[ 'name' => $column, array $orderBy = ['nomSalle' => 'ASC'], $limit, $offset)
        return $this->findBy([], ['id' => 'DESC'], 50);
    }
}
