<?php

namespace AppBundle\Repository;

/**
 * ImageGallerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageGallerieRepository extends \Doctrine\ORM\EntityRepository
{
}
