<?php

namespace AppBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $client
     * @return array
     */
    public function getReservationByClient($client){

        //var_dump('hello genre'); die;
        $queryBuilder = $this->createQueryBuilder('r');

        $query = $queryBuilder
            ->select('r')
            ->where('r.client =:client')
            ->setParameter('client', $client)
            ->getQuery();
        $results = $query->getResult();
        return $results;
    }

    //recherche par nom client approximatif dans Client !!!!!!!!!!!!!!
    public function getClientReservation($name){
        //crée objet constructeur de requete sur table r
        $queryBuilder = $this->createQueryBuilder('r');
        // utilisation du LIKE avec controle entrée setParameter;
        $query = $queryBuilder
            ->select('r')
           /* ->leftJoin('AppBundle\Entity\Client', 'c')*/
            ->leftJoin('r.client', 'c')
            ->where('c.nomClient LIKE :nomClient')
            ->setParameter('nomClient', '%'.$name.'%') // sécurité injection !!!
            ->getQuery(); /// important ! à ajouter setParameter
        $results = $query->getResult();
        return $results;
    }
}
