<?php

namespace AppBundle\Repository;

/**
 * SalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findAll(){
        //requête en alphabétique
        return $this->findBy(array(), ['nomSalle' => 'ASC']);
    }
}