<?php

namespace AppBundle\Repository;

/**
 * SpectateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpectateurRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findAll(){
        //requête en alphabétique
        return $this->findBy(array(), ['nomSpectateur' => 'ASC']);
    }
}
